### PR TITLE
3/3 Clean up tests

### PR DESCRIPTION
**Pull request by djanowski**
Superset of #15 and #16, also cleans up tests.

### CODE REVIEW

**Comment by deitch** [comment]
So, this is a superset and can be merged in and then just close #15 and #16?

**Comment by djanowski** [comment]
Exactly, this includes the other two (and GitHub will probably close the others automatically).

**Comment by deitch** [comment]
So version bump and we can merge?

**Comment by djanowski** [comment]
I usually bump in master directly after merging PRs but do you want me to
do it here?

**Comment by deitch** [comment]
Yeah, let us just do it here. I like treating `master` as protected.

**Comment by djanowski** [comment]
Done!

**Comment by deitch** [comment]
And merged!

**Pull request merged**
