### PR TITLE
feat: add type definitions

### LINKED ISSUE #24: TypeScript definitions
Hey! Looking to try this library out, but I can't seem to find any TypeScript defintions anywhere. Is this something that is planned or could be considered? :)

### PR DESCRIPTION
**Pull request by nicktrn**
Fixes #24 

Builds on the previous work by @anton-johansson in https://github.com/deitch/smtp-tester/issues/24#issuecomment-1177372165

### CODE REVIEW

**Comment by nicktrn** [comment]
Thanks for merging this so quickly!

**Comment by anton-johansson** [comment]
This is awesome! @deitch, would it be possible to get a new release out with these changes? :partying_face:

**Comment by deitch** [comment]
Done. Takes a few mins

**Comment by deitch** [comment]
Or... maybe the publish pipeline doesn't exist here. Other projects have it. I will push it out manually.

**Comment by deitch** [comment]
Done

**Pull request merged**
